[package]
name = "cv"
version = "0.1.0"
authors = ["zu1k <i@lgf.im>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.53"
